#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: setwall /path/to/image.jpg"
  exit 1
fi

WALL_PATH="$(realpath "$1")"
CONFIG_PATH="~/.config/hypr/hyprpaper.conf"

cat > "$CONFIG_PATH" <<EOF
preload = $WALL_PATH
wallpaper = ,$WALL_PATH
ipc = on
EOF

hyprctl hyprpaper reload ,"$WALL_PATH" >/dev/null 2>&1

wal -i "$WALL_PATH" >/dev/null 2>&1

killall waybar >/dev/null 2>&1
nohup waybar >/dev/null 2>&1 &

